# Site
name: 'Hardware Happy Hour'
description: 'A place for technologist and enthusiasts to discuss their latest projects in a social atmosphere'
url: 'https://hardwarehappyhour.com'
#logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
#baseurl: ''
#disqus:
email: 'hello@hardwarehappyhour.com'
#mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag 

collections:
  groups:
    output: true

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      image: /assets/images/xMVIMG_20191203_201342-scaled-e1577129468500.jpg.pagespeed.ic.qSe7ecMQnz.webp
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  # all groups
  - scope:
      path: "_groups"
    values:
      layout: group

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]